// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF7vyMJeIXFHgGrbhoE2ByI9ZRJTEi-jI',
    appId: '1:168455003896:web:244806bc109f4e4b22250d',
    messagingSenderId: '168455003896',
    projectId: 'erudite-acre-257914',
    authDomain: 'erudite-acre-257914.firebaseapp.com',
    storageBucket: 'erudite-acre-257914.appspot.com',
    measurementId: 'G-V2RQ24TZBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxsk-G3xtYwpWmAgg-fnSJA-AmnRBvW_A',
    appId: '1:168455003896:android:d48ac4f71618c7b222250d',
    messagingSenderId: '168455003896',
    projectId: 'erudite-acre-257914',
    storageBucket: 'erudite-acre-257914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCznbBsAo0ELmoDauW5DOWI3jpe9BPg0cA',
    appId: '1:168455003896:ios:29b8d82c696d847722250d',
    messagingSenderId: '168455003896',
    projectId: 'erudite-acre-257914',
    storageBucket: 'erudite-acre-257914.appspot.com',
    iosClientId: '168455003896-ovv6bgig7lsl3a4849g183uqa5mq7c6j.apps.googleusercontent.com',
    iosBundleId: 'com.matteopolak.geonotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCznbBsAo0ELmoDauW5DOWI3jpe9BPg0cA',
    appId: '1:168455003896:ios:29b8d82c696d847722250d',
    messagingSenderId: '168455003896',
    projectId: 'erudite-acre-257914',
    storageBucket: 'erudite-acre-257914.appspot.com',
    iosClientId: '168455003896-ovv6bgig7lsl3a4849g183uqa5mq7c6j.apps.googleusercontent.com',
    iosBundleId: 'com.matteopolak.geonotes',
  );
}
